spring:
    application:
        name: manager
    profiles:
        active: @spring.profiles.active@
    jackson:
        serialization.write_dates_as_timestamps: true
    mvc:
        favicon:
            enabled: false
    messages:
      basename: i18n/messages
      cache-seconds: 3600
server:
    session:
        cookie:
            http-only: true
        timeout: 36000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
quartz:
  enabled: true
mybatis:
  type-aliases-package: cn.fintecher.entity
  mapper-locations: classpath:mapper/*.xml

# 是否允許重複登錄 1 表示允許  0 表示不允許
duplicateLogin: 1
sessionTimeout: 600
#允许用户密码错误次数
loginErrorLimit: 99


localelist: zh_CN,en

