spring:
    application:
        name: file-service
    profiles:
        active: @spring.profiles.active@
    jackson:
        serialization.write_dates_as_timestamps: true
    mvc:
        favicon:
            enabled: false
    messages:
      basename: i18n/messages
      cache-seconds: 3600
    http:
      multipart:
        max-request-size: 1024MB
        max-file-size: 1024MB
server:
    session:
        cookie:
            http-only: true
        timeout: 36000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
quartz:
  enabled: true

gridfs:
  path: 127.0.0.1:9000/file-service

