spring:
    application:
        name: app-service
    profiles:
        active: @spring.profiles.active@
    jackson:
        serialization.write_dates_as_timestamps: true
    mvc:
        favicon:
            enabled: false
    messages:
      basename: i18n/messages
      cache-seconds: 3600
server:
    session:
        cookie:
            http-only: true
        timeout: 36000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
quartz:
  enabled: true
mybatis:
  type-aliases-package: cn.fintecher.entity
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
# 是否允許重複登錄 1 表示允許  0 表示不允許
duplicateLogin: 1
sessionTimeout: 600
#允许用户密码错误次数
loginErrorLimit: 99


localelist: zh_CN,en

#APP允许用户每天密码错误次数
loginErrorCount: 10


#ocr固定参数
ocr:
  url: https://idasc.webank.com
  version: 1.0.0
  type_nonce: NONCE
  type_sign: SIGN
  grant_type: client_credential
  #腾讯云
  faceResultUrl: https://idasc.webank.com/api/server/sync
  singVersion: 1.0.0

#阿里的根据银行卡号码获取银行卡归属地信息
cardInfo:
  path: https://ccdcapi.alipay.com/validateAndCacheCardInfo.json

